// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Data.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applicants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8886),
                            District = "City of Westminster",
                            Email = "user1@example.com",
                            Fullname = "James Smith",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "1234567890",
                            Province = "Greater London",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "Westminster"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1995, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8889),
                            District = "Manchester City",
                            Email = "user2@example.com",
                            Fullname = "Sarah Johnson",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "2345678901",
                            Province = "Greater Manchester",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "City Centre"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1985, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8892),
                            District = "Birmingham City Centre",
                            Email = "user3@example.com",
                            Fullname = "David Williams",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "3456789012",
                            Province = "West Midlands",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "Ladywood"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1980, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8896),
                            District = "Liverpool City Centre",
                            Email = "user4@example.com",
                            Fullname = "Emma Brown",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "4567890123",
                            Province = "Merseyside",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "Riverside"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1992, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8899),
                            District = "Leeds City Centre",
                            Email = "user5@example.com",
                            Fullname = "John Jones",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "5678901234",
                            Province = "West Yorkshire",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "City Centre"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1978, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8902),
                            District = "Bristol City Centre",
                            Email = "user6@example.com",
                            Fullname = "Lucy Taylor",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "6789012345",
                            Province = "Bristol",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "Central"
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1988, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8905),
                            District = "Sheffield City Centre",
                            Email = "user7@example.com",
                            Fullname = "Michael Davies",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "7890123456",
                            Province = "South Yorkshire",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "City Centre"
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1998, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8908),
                            District = "Newcastle City Centre",
                            Email = "user8@example.com",
                            Fullname = "Olivia Wilson",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "8901234567",
                            Province = "Tyne and Wear",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "Ouseburn"
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateTime(1983, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8911),
                            District = "Nottingham City Centre",
                            Email = "user9@example.com",
                            Fullname = "Thomas Evans",
                            Image = "assets\\client\\img\\img-applicant\\default-image-applicant.png",
                            Password = "Abc12345678",
                            Phone = "9012345678",
                            Province = "Nottinghamshire",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ward = "Bridge"
                        });
                });

            modelBuilder.Entity("Project.Data.ApplicantVacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Applicant_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Attachment")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hr_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StatusApplicant_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vacancy_Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Applicant_Id");

                    b.HasIndex("Hr_Id");

                    b.HasIndex("StatusApplicant_Id");

                    b.HasIndex("Vacancy_Id");

                    b.ToTable("ApplicantsVacancies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Applicant_Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9242),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0001"
                        },
                        new
                        {
                            Id = 2,
                            Applicant_Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9244),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0002"
                        },
                        new
                        {
                            Id = 3,
                            Applicant_Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9246),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0003"
                        },
                        new
                        {
                            Id = 4,
                            Applicant_Id = 4,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9248),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0004"
                        },
                        new
                        {
                            Id = 5,
                            Applicant_Id = 5,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9250),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0005"
                        },
                        new
                        {
                            Id = 6,
                            Applicant_Id = 6,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9252),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0001"
                        },
                        new
                        {
                            Id = 7,
                            Applicant_Id = 7,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9254),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0002"
                        },
                        new
                        {
                            Id = 8,
                            Applicant_Id = 8,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9256),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0003"
                        },
                        new
                        {
                            Id = 9,
                            Applicant_Id = 9,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9258),
                            StatusApplicant_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0004"
                        });
                });

            modelBuilder.Entity("Project.Data.Department", b =>
                {
                    b.Property<string>("Department_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Department_Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Department_Id = "D0001",
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8706),
                            Name = "Information Technology",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Department_Id = "D0002",
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8719),
                            Name = "Desgin",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Department_Id = "D0003",
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8720),
                            Name = "Marketing",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Data.InterviewVacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ApplicantVacancy_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interview_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusInterview_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantVacancy_Id");

                    b.HasIndex("Interview_Id");

                    b.HasIndex("StatusInterview_Id");

                    b.ToTable("InterviewsVacancies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantVacancy_Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9282),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ApplicantVacancy_Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9284),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ApplicantVacancy_Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9286),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ApplicantVacancy_Id = 4,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9288),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ApplicantVacancy_Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9290),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ApplicantVacancy_Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9292),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ApplicantVacancy_Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9294),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            ApplicantVacancy_Id = 4,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9295),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            ApplicantVacancy_Id = 5,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9297),
                            StatusInterview_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Data.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Department_Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8938),
                            Department_Id = "D0001",
                            Name = "C#",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8940),
                            Department_Id = "D0001",
                            Name = "Java",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8942),
                            Department_Id = "D0001",
                            Name = "PHP",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8944),
                            Department_Id = "D0002",
                            Name = "Adobe Creative Suite",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8945),
                            Department_Id = "D0002",
                            Name = "Sketch",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8947),
                            Department_Id = "D0002",
                            Name = "Figma",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8949),
                            Department_Id = "D0003",
                            Name = "Google Analytics",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8951),
                            Department_Id = "D0003",
                            Name = "SEO",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8952),
                            Department_Id = "D0003",
                            Name = "Google AdWords , Facebook Ads",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Data.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8978),
                            Name = "Intern",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8980),
                            Name = "Fresher",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8982),
                            Name = "Junior",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8983),
                            Name = "Senior",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(8985),
                            Name = "Leader",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Data.StatusApplicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StatusApplicants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9005),
                            Name = "Not Process",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9006),
                            Name = "In Process",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9008),
                            Name = "Hired",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9010),
                            Name = "Banned",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Data.StatusInterview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StatusInterviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9054),
                            Name = "Processing",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9056),
                            Name = "Scheduled",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9057),
                            Name = "Selected",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9059),
                            Name = "Rejected",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Data.StatusVacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StatusVacancies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9030),
                            Name = "Open",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9032),
                            Name = "Close",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9033),
                            Name = "Suspended",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Data.Vacancy", b =>
                {
                    b.Property<string>("Vacancy_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hr_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Requirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("StatusVacancy_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Vacancy_Id");

                    b.HasIndex("Hr_Id");

                    b.HasIndex("Position_Id");

                    b.HasIndex("StatusVacancy_Id");

                    b.ToTable("Vacancies");

                    b.HasData(
                        new
                        {
                            Vacancy_Id = "V0001",
                            Benefits = "Benefits",
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9087),
                            Description = "Description",
                            EndDate = new DateTime(2023, 12, 8, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9081),
                            Place = "America",
                            Position_Id = 1,
                            Quantity = 5,
                            Requirement = "Requirement",
                            Salary = 2000,
                            StatusVacancy_Id = 1,
                            Title = "Title",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Vacancy_Id = "V0002",
                            Benefits = "Benefits",
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9158),
                            Description = "Description",
                            EndDate = new DateTime(2023, 12, 8, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9156),
                            Place = "America",
                            Position_Id = 2,
                            Quantity = 4,
                            Requirement = "Requirement",
                            Salary = 7000,
                            StatusVacancy_Id = 1,
                            Title = "Title",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Vacancy_Id = "V0003",
                            Benefits = "Benefits",
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9162),
                            Description = "Description",
                            EndDate = new DateTime(2023, 12, 8, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9161),
                            Place = "America",
                            Position_Id = 3,
                            Quantity = 3,
                            Requirement = "Requirement",
                            Salary = 10000,
                            StatusVacancy_Id = 1,
                            Title = "Title",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Vacancy_Id = "V0004",
                            Benefits = "Benefits",
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9166),
                            Description = "Description",
                            EndDate = new DateTime(2023, 12, 8, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9165),
                            Place = "America",
                            Position_Id = 4,
                            Quantity = 2,
                            Requirement = "Requirement",
                            Salary = 13000,
                            StatusVacancy_Id = 1,
                            Title = "Title",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Vacancy_Id = "V0005",
                            Benefits = "Benefits",
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9170),
                            Description = "Description",
                            EndDate = new DateTime(2023, 12, 8, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9169),
                            Place = "America",
                            Position_Id = 5,
                            Quantity = 1,
                            Requirement = "Requirement",
                            Salary = 15000,
                            StatusVacancy_Id = 1,
                            Title = "Title",
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Data.VacancyJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Job_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vacancy_Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Job_Id");

                    b.HasIndex("Vacancy_Id");

                    b.ToTable("VacanciesJobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9192),
                            Job_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0001"
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9194),
                            Job_Id = 2,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0001"
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9196),
                            Job_Id = 3,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0001"
                        },
                        new
                        {
                            Id = 4,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9198),
                            Job_Id = 4,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0002"
                        },
                        new
                        {
                            Id = 5,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9199),
                            Job_Id = 5,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0002"
                        },
                        new
                        {
                            Id = 6,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9201),
                            Job_Id = 6,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0002"
                        },
                        new
                        {
                            Id = 7,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9203),
                            Job_Id = 7,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0003"
                        },
                        new
                        {
                            Id = 8,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9205),
                            Job_Id = 8,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0003"
                        },
                        new
                        {
                            Id = 9,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9207),
                            Job_Id = 9,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0003"
                        },
                        new
                        {
                            Id = 10,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9209),
                            Job_Id = 1,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0004"
                        },
                        new
                        {
                            Id = 11,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9210),
                            Job_Id = 2,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0004"
                        },
                        new
                        {
                            Id = 12,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9212),
                            Job_Id = 3,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0004"
                        },
                        new
                        {
                            Id = 13,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9214),
                            Job_Id = 4,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0005"
                        },
                        new
                        {
                            Id = 14,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9216),
                            Job_Id = 5,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0005"
                        },
                        new
                        {
                            Id = 15,
                            Created_at = new DateTime(2023, 11, 28, 19, 55, 12, 219, DateTimeKind.Local).AddTicks(9218),
                            Job_Id = 6,
                            Updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vacancy_Id = "V0005"
                        });
                });

            modelBuilder.Entity("Project.Data.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employeecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Department_Id");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Data.ApplicantVacancy", b =>
                {
                    b.HasOne("Project.Data.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("Applicant_Id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("Hr_Id");

                    b.HasOne("Project.Data.StatusApplicant", "StatusApplicant")
                        .WithMany()
                        .HasForeignKey("StatusApplicant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Data.Vacancy", "Vacancy")
                        .WithMany()
                        .HasForeignKey("Vacancy_Id");

                    b.Navigation("Applicant");

                    b.Navigation("IdentityUser");

                    b.Navigation("StatusApplicant");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Project.Data.InterviewVacancy", b =>
                {
                    b.HasOne("Project.Data.ApplicantVacancy", "ApplicantVacancy")
                        .WithMany()
                        .HasForeignKey("ApplicantVacancy_Id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("Interview_Id");

                    b.HasOne("Project.Data.StatusInterview", "StatusInterview")
                        .WithMany()
                        .HasForeignKey("StatusInterview_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicantVacancy");

                    b.Navigation("IdentityUser");

                    b.Navigation("StatusInterview");
                });

            modelBuilder.Entity("Project.Data.Job", b =>
                {
                    b.HasOne("Project.Data.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Department_Id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Project.Data.Vacancy", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("Hr_Id");

                    b.HasOne("Project.Data.Position", "Position")
                        .WithMany()
                        .HasForeignKey("Position_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Data.StatusVacancy", "StatusVacancy")
                        .WithMany()
                        .HasForeignKey("StatusVacancy_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");

                    b.Navigation("Position");

                    b.Navigation("StatusVacancy");
                });

            modelBuilder.Entity("Project.Data.VacancyJob", b =>
                {
                    b.HasOne("Project.Data.Job", "Job")
                        .WithMany("VacanciesJobs")
                        .HasForeignKey("Job_Id");

                    b.HasOne("Project.Data.Vacancy", "Vacancy")
                        .WithMany("VacanciesJobs")
                        .HasForeignKey("Vacancy_Id");

                    b.Navigation("Job");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Project.Data.AppUser", b =>
                {
                    b.HasOne("Project.Data.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Department_Id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Project.Data.Job", b =>
                {
                    b.Navigation("VacanciesJobs");
                });

            modelBuilder.Entity("Project.Data.Vacancy", b =>
                {
                    b.Navigation("VacanciesJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
